<?php

namespace App\Enums;

use Filament\Support\Contracts\HasLabel;

enum CountryEnum: string implements HasLabel
{
    case AFGHANISTAN = 'afghanistan';
    case ALBANIA = 'albania';
    case ALGERIA = 'algeria';
    case ANDORRA = 'andorra';
    case ANGOLA = 'angola';
    case ANTIGUA_AND_BARBUDA = 'antigua_and_barbuda';
    case ARGENTINA = 'argentina';
    case ARMENIA = 'armenia';
    case AUSTRALIA = 'australia';
    case AUSTRIA = 'austria';
    case AZERBAIJAN = 'azerbaijan';
    case BAHAMAS = 'bahamas';
    case BAHRAIN = 'bahrain';
    case BANGLADESH = 'bangladesh';
    case BARBADOS = 'barbados';
    case BELARUS = 'belarus';
    case BELGIUM = 'belgium';
    case BELIZE = 'belize';
    case BENIN = 'benin';
    case BHUTAN = 'bhutan';
    case BOLIVIA = 'bolivia';
    case BOSNIA_AND_HERZEGOVINA = 'bosnia_and_herzegovina';
    case BOTSWANA = 'botswana';
    case BRAZIL = 'brazil';
    case BRUNEI = 'brunei';
    case BULGARIA = 'bulgaria';
    case BURKINA_FASO = 'burkina_faso';
    case BURUNDI = 'burundi';
    case CABO_VERDE = 'cabo_verde';
    case CAMBODIA = 'cambodia';
    case CAMEROON = 'cameroon';
    case CANADA = 'canada';
    case CENTRAL_AFRICAN_REPUBLIC = 'central_african_republic';
    case CHAD = 'chad';
    case CHILE = 'chile';
    case CHINA = 'china';
    case COLOMBIA = 'colombia';
    case COMOROS = 'comoros';
    case CONGO = 'congo';
    case COSTA_RICA = 'costa_rica';
    case COTE_DIVOIRE = 'cote_divoire';
    case CROATIA = 'croatia';
    case CUBA = 'cuba';
    case CYPRUS = 'cyprus';
    case CZECH_REPUBLIC = 'czech_republic';
    case DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'democratic_republic_of_the_congo';
    case DENMARK = 'denmark';
    case DJIBOUTI = 'djibouti';
    case DOMINICA = 'dominica';
    case DOMINICAN_REPUBLIC = 'dominican_republic';
    case EAST_TIMOR = 'east_timor';
    case ECUADOR = 'ecuador';
    case EGYPT = 'egypt';
    case EL_SALVADOR = 'el_salvador';
    case EQUATORIAL_GUINEA = 'equatorial_guinea';
    case ERITREA = 'eritrea';
    case ESTONIA = 'estonia';
    case ESWATINI = 'eswatini';
    case ETHIOPIA = 'ethiopia';
    case FIJI = 'fiji';
    case FINLAND = 'finland';
    case FRANCE = 'france';
    case GABON = 'gabon';
    case GAMBIA = 'gambia';
    case GEORGIA = 'georgia';
    case GERMANY = 'germany';
    case GHANA = 'ghana';
    case GREECE = 'greece';
    case GRENADA = 'grenada';
    case GUATEMALA = 'guatemala';
    case GUINEA = 'guinea';
    case GUINEA_BISSAU = 'guinea_bissau';
    case GUYANA = 'guyana';
    case HAITI = 'haiti';
    case HONDURAS = 'honduras';
    case HUNGARY = 'hungary';
    case ICELAND = 'iceland';
    case INDIA = 'india';
    case INDONESIA = 'indonesia';
    case IRAN = 'iran';
    case IRAQ = 'iraq';
    case IRELAND = 'ireland';
    case ISRAEL = 'israel';
    case ITALY = 'italy';
    case JAMAICA = 'jamaica';
    case JAPAN = 'japan';
    case JORDAN = 'jordan';
    case KAZAKHSTAN = 'kazakhstan';
    case KENYA = 'kenya';
    case KIRIBATI = 'kiribati';
    case KOSOVO = 'kosovo';
    case KUWAIT = 'kuwait';
    case KYRGYZSTAN = 'kyrgyzstan';
    case LAOS = 'laos';
    case LATVIA = 'latvia';
    case LEBANON = 'lebanon';
    case LESOTHO = 'lesotho';
    case LIBERIA = 'liberia';
    case LIBYA = 'libya';
    case LIECHTENSTEIN = 'liechtenstein';
    case LITHUANIA = 'lithuania';
    case LUXEMBOURG = 'luxembourg';
    case MADAGASCAR = 'madagascar';
    case MALAWI = 'malawi';
    case MALAYSIA = 'malaysia';
    case MALDIVES = 'maldives';
    case MALI = 'mali';
    case MALTA = 'malta';
    case MARSHALL_ISLANDS = 'marshall_islands';
    case MAURITANIA = 'mauritania';
    case MAURITIUS = 'mauritius';
    case MEXICO = 'mexico';
    case MICRONESIA = 'micronesia';
    case MOLDOVA = 'moldova';
    case MONACO = 'monaco';
    case MONGOLIA = 'mongolia';
    case MONTENEGRO = 'montenegro';
    case MOROCCO = 'morocco';
    case MOZAMBIQUE = 'mozambique';
    case MYANMAR = 'myanmar';
    case NAMIBIA = 'namibia';
    case NAURU = 'nauru';
    case NEPAL = 'nepal';
    case NETHERLANDS = 'netherlands';
    case NEW_ZEALAND = 'new_zealand';
    case NICARAGUA = 'nicaragua';
    case NIGER = 'niger';
    case NIGERIA = 'nigeria';
    case NORTH_KOREA = 'north_korea';
    case NORTH_MACEDONIA = 'north_macedonia';
    case NORWAY = 'norway';
    case OMAN = 'oman';
    case PAKISTAN = 'pakistan';
    case PALAU = 'palau';
    case PALESTINE = 'palestine';
    case PANAMA = 'panama';
    case PAPUA_NEW_GUINEA = 'papua_new_guinea';
    case PARAGUAY = 'paraguay';
    case PERU = 'peru';
    case PHILIPPINES = 'philippines';
    case POLAND = 'poland';
    case PORTUGAL = 'portugal';
    case QATAR = 'qatar';
    case ROMANIA = 'romania';
    case RUSSIA = 'russia';
    case RWANDA = 'rwanda';
    case SAINT_KITTS_AND_NEVIS = 'saint_kitts_and_nevis';
    case SAINT_LUCIA = 'saint_lucia';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'saint_vincent_and_the_grenadines';
    case SAMOA = 'samoa';
    case SAN_MARINO = 'san_marino';
    case SAO_TOME_AND_PRINCIPE = 'sao_tome_and_principe';
    case SAUDI_ARABIA = 'saudi_arabia';
    case SENEGAL = 'senegal';
    case SERBIA = 'serbia';
    case SEYCHELLES = 'seychelles';
    case SIERRA_LEONE = 'sierra_leone';
    case SINGAPORE = 'singapore';
    case SLOVAKIA = 'slovakia';
    case SLOVENIA = 'slovenia';
    case SOLOMON_ISLANDS = 'solomon_islands';
    case SOMALIA = 'somalia';
    case SOUTH_AFRICA = 'south_africa';
    case SOUTH_KOREA = 'south_korea';
    case SOUTH_SUDAN = 'south_sudan';
    case SPAIN = 'spain';
    case SRI_LANKA = 'sri_lanka';
    case SUDAN = 'sudan';
    case SURINAME = 'suriname';
    case SWEDEN = 'sweden';
    case SWITZERLAND = 'switzerland';
    case SYRIA = 'syria';
    case TAIWAN = 'taiwan';
    case TAJIKISTAN = 'tajikistan';
    case TANZANIA = 'tanzania';
    case THAILAND = 'thailand';
    case TOGO = 'togo';
    case TONGA = 'tonga';
    case TRINIDAD_AND_TOBAGO = 'trinidad_and_tobago';
    case TUNISIA = 'tunisia';
    case TURKEY = 'turkey';
    case TURKMENISTAN = 'turkmenistan';
    case TUVALU = 'tuvalu';
    case UGANDA = 'uganda';
    case UKRAINE = 'ukraine';
    case UNITED_ARAB_EMIRATES = 'united_arab_emirates';
    case UNITED_KINGDOM = 'united_kingdom';
    case UNITED_STATES = 'united_states';
    case URUGUAY = 'uruguay';
    case UZBEKISTAN = 'uzbekistan';
    case VANUATU = 'vanuatu';
    case VATICAN_CITY = 'vatican_city';
    case VENEZUELA = 'venezuela';
    case VIETNAM = 'vietnam';
    case YEMEN = 'yemen';
    case ZAMBIA = 'zambia';
    case ZIMBABWE = 'zimbabwe';

    public function getLabel(): ?string
    {
        return $this->name;

        // or

        return match ($this) {
            self::AFGHANISTAN => 'Afghanistan',
            self::ALBANIA => 'Albania',
            self::ALGERIA => 'Algeria',
            self::ANDORRA => 'Andorra',
            self::ANGOLA => 'Angola',
            self::ANTIGUA_AND_BARBUDA => 'Antigua and Barbuda',
            self::ARGENTINA => 'Argentina',
            self::ARMENIA => 'Armenia',
            self::AUSTRALIA => 'Australia',
            self::AUSTRIA => 'Austria',
            self::AZERBAIJAN => 'Azerbaijan',
            self::BAHAMAS => 'Bahamas',
            self::BAHRAIN => 'Bahrain',
            self::BANGLADESH => 'Bangladesh',
            self::BARBADOS => 'Barbados',
            self::BELARUS => 'Belarus',
            self::BELGIUM => 'Belgium',
            self::BELIZE => 'Belize',
            self::BENIN => 'Benin',
            self::BHUTAN => 'Bhutan',
            self::BOLIVIA => 'Bolivia',
            self::BOSNIA_AND_HERZEGOVINA => 'Bosnia and Herzegovina',
            self::BOTSWANA => 'Botswana',
            self::BRAZIL => 'Brazil',
            self::BRUNEI => 'Brunei',
            self::BULGARIA => 'Bulgaria',
            self::BURKINA_FASO => 'Burkina Faso',
            self::BURUNDI => 'Burundi',
            self::CABO_VERDE => 'Cabo Verde',
            self::CAMBODIA => 'Cambodia',
            self::CAMEROON => 'Cameroon',
            self::CANADA => 'Canada',
            self::CENTRAL_AFRICAN_REPUBLIC => 'Central African Republic',
            self::CHAD => 'Chad',
            self::CHILE => 'Chile',
            self::CHINA => 'China',
            self::COLOMBIA => 'Colombia',
            self::COMOROS => 'Comoros',
            self::CONGO => 'Congo',
            self::COSTA_RICA => 'Costa Rica',
            self::COTE_DIVOIRE => "Côte d'Ivoire",
            self::CROATIA => 'Croatia',
            self::CUBA => 'Cuba',
            self::CYPRUS => 'Cyprus',
            self::CZECH_REPUBLIC => 'Czech Republic',
            self::DEMOCRATIC_REPUBLIC_OF_THE_CONGO => 'Democratic Republic of the Congo',
            self::DENMARK => 'Denmark',
            self::DJIBOUTI => 'Djibouti',
            self::DOMINICA => 'Dominica',
            self::DOMINICAN_REPUBLIC => 'Dominican Republic',
            self::EAST_TIMOR => 'East Timor',
            self::ECUADOR => 'Ecuador',
            self::EGYPT => 'Egypt',
            self::EL_SALVADOR => 'El Salvador',
            self::EQUATORIAL_GUINEA => 'Equatorial Guinea',
            self::ERITREA => 'Eritrea',
            self::ESTONIA => 'Estonia',
            self::ESWATINI => 'Eswatini',
            self::ETHIOPIA => 'Ethiopia',
            self::FIJI => 'Fiji',
            self::FINLAND => 'Finland',
            self::FRANCE => 'France',
            self::GABON => 'Gabon',
            self::GAMBIA => 'Gambia',
            self::GEORGIA => 'Georgia',
            self::GERMANY => 'Germany',
            self::GHANA => 'Ghana',
            self::GREECE => 'Greece',
            self::GRENADA => 'Grenada',
            self::GUATEMALA => 'Guatemala',
            self::GUINEA => 'Guinea',
            self::GUINEA_BISSAU => 'Guinea-Bissau',
            self::GUYANA => 'Guyana',
            self::HAITI => 'Haiti',
            self::HONDURAS => 'Honduras',
            self::HUNGARY => 'Hungary',
            self::ICELAND => 'Iceland',
            self::INDIA => 'India',
            self::INDONESIA => 'Indonesia',
            self::IRAN => 'Iran',
            self::IRAQ => 'Iraq',
            self::IRELAND => 'Ireland',
            self::ISRAEL => 'Israel',
            self::ITALY => 'Italy',
            self::JAMAICA => 'Jamaica',
            self::JAPAN => 'Japan',
            self::JORDAN => 'Jordan',
            self::KAZAKHSTAN => 'Kazakhstan',
            self::KENYA => 'Kenya',
            self::KIRIBATI => 'Kiribati',
            self::KOSOVO => 'Kosovo',
            self::KUWAIT => 'Kuwait',
            self::KYRGYZSTAN => 'Kyrgyzstan',
            self::LAOS => 'Laos',
            self::LATVIA => 'Latvia',
            self::LEBANON => 'Lebanon',
            self::LESOTHO => 'Lesotho',
            self::LIBERIA => 'Liberia',
            self::LIBYA => 'Libya',
            self::LIECHTENSTEIN => 'Liechtenstein',
            self::LITHUANIA => 'Lithuania',
            self::LUXEMBOURG => 'Luxembourg',
            self::MADAGASCAR => 'Madagascar',
            self::MALAWI => 'Malawi',
            self::MALAYSIA => 'Malaysia',
            self::MALDIVES => 'Maldives',
            self::MALI => 'Mali',
            self::MALTA => 'Malta',
            self::MARSHALL_ISLANDS => 'Marshall Islands',
            self::MAURITANIA => 'Mauritania',
            self::MAURITIUS => 'Mauritius',
            self::MEXICO => 'Mexico',
            self::MICRONESIA => 'Micronesia',
            self::MOLDOVA => 'Moldova',
            self::MONACO => 'Monaco',
            self::MONGOLIA => 'Mongolia',
            self::MONTENEGRO => 'Montenegro',
            self::MOROCCO => 'Morocco',
            self::MOZAMBIQUE => 'Mozambique',
            self::MYANMAR => 'Myanmar',
            self::NAMIBIA => 'Namibia',
            self::NAURU => 'Nauru',
            self::NEPAL => 'Nepal',
            self::NETHERLANDS => 'Netherlands',
            self::NEW_ZEALAND => 'New Zealand',
            self::NICARAGUA => 'Nicaragua',
            self::NIGER => 'Niger',
            self::NIGERIA => 'Nigeria',
            self::NORTH_KOREA => 'North Korea',
            self::NORTH_MACEDONIA => 'North Macedonia',
            self::NORWAY => 'Norway',
            self::OMAN => 'Oman',
            self::PAKISTAN => 'Pakistan',
            self::PALAU => 'Palau',
            self::PALESTINE => 'Palestine',
            self::PANAMA => 'Panama',
            self::PAPUA_NEW_GUINEA => 'Papua New Guinea',
            self::PARAGUAY => 'Paraguay',
            self::PERU => 'Peru',
            self::PHILIPPINES => 'Philippines',
            self::POLAND => 'Poland',
            self::PORTUGAL => 'Portugal',
            self::QATAR => 'Qatar',
            self::ROMANIA => 'Romania',
            self::RUSSIA => 'Russia',
            self::RWANDA => 'Rwanda',
            self::SAINT_KITTS_AND_NEVIS => 'Saint Kitts and Nevis',
            self::SAINT_LUCIA => 'Saint Lucia',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'Saint Vincent and the Grenadines',
            self::SAMOA => 'Samoa',
            self::SAN_MARINO => 'San Marino',
            self::SAO_TOME_AND_PRINCIPE => 'Sao Tome and Principe',
            self::SAUDI_ARABIA => 'Saudi Arabia',
            self::SENEGAL => 'Senegal',
            self::SERBIA => 'Serbia',
            self::SEYCHELLES => 'Seychelles',
            self::SIERRA_LEONE => 'Sierra Leone',
            self::SINGAPORE => 'Singapore',
            self::SLOVAKIA => 'Slovakia',
            self::SLOVENIA => 'Slovenia',
            self::SOLOMON_ISLANDS => 'Solomon Islands',
            self::SOMALIA => 'Somalia',
            self::SOUTH_AFRICA => 'South Africa',
            self::SOUTH_KOREA => 'South Korea',
            self::SOUTH_SUDAN => 'South Sudan',
            self::SPAIN => 'Spain',
            self::SRI_LANKA => 'Sri Lanka',
            self::SUDAN => 'Sudan',
            self::SURINAME => 'Suriname',
            self::SWEDEN => 'Sweden',
            self::SWITZERLAND => 'Switzerland',
            self::SYRIA => 'Syria',
            self::TAIWAN => 'Taiwan',
            self::TAJIKISTAN => 'Tajikistan',
            self::TANZANIA => 'Tanzania',
            self::THAILAND => 'Thailand',
            self::TOGO => 'Togo',
            self::TONGA => 'Tonga',
            self::TRINIDAD_AND_TOBAGO => 'Trinidad and Tobago',
            self::TUNISIA => 'Tunisia',
            self::TURKEY => 'Turkey',
            self::TURKMENISTAN => 'Turkmenistan',
            self::TUVALU => 'Tuvalu',
            self::UGANDA => 'Uganda',
            self::UKRAINE => 'Ukraine',
            self::UNITED_ARAB_EMIRATES => 'United Arab Emirates',
            self::UNITED_KINGDOM => 'United Kingdom',
            self::UNITED_STATES => 'United States',
            self::URUGUAY => 'Uruguay',
            self::UZBEKISTAN => 'Uzbekistan',
            self::VANUATU => 'Vanuatu',
            self::VATICAN_CITY => 'Vatican City',
            self::VENEZUELA => 'Venezuela',
            self::VIETNAM => 'Vietnam',
            self::YEMEN => 'Yemen',
            self::ZAMBIA => 'Zambia',
            self::ZIMBABWE => 'Zimbabwe',
        };
    }
}
